test:
  service: Disk
  root: <%= Rails.root.join("public") %>

local:
  service: Disk
  root: <%= Rails.root.join("public") %>

aliyun: &aliyun
  service: Aliyun
  access_key_id: <%= Rails.application.credentials.config[:oss][:id] %>
  access_key_secret: <%= Rails.application.credentials.config[:oss][:key] %>
  endpoint: oss-cn-beijing.aliyuncs.com
  
aliyun_development:
  <<: *aliyun
  bucket: msmi-mapplaytest

aliyun_production:
  <<: *aliyun
  bucket: msmi-mapplaytest

#EDITOR=vim bin/rails credentials:edit 
# ================== 关于本地存储和云存储的使用 =======================
# 本地存储：
#   用于内部网络、私有服务器环境
#   文件需要放在静态资源目录或服务器，供客户端访问
#   需要手动处理文件预览图和生命周期

# 云存储：
#   用于公开服务网络和托管服务器
#   使用OSS提供的功能获取预览图，设置文件生命周期
#   客户端直传（未完成）

# Use rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
# amazon:
#   service: S3
#   access_key_id: <%= Rails.application.credentials.dig(:aws, :access_key_id) %>
#   secret_access_key: <%= Rails.application.credentials.dig(:aws, :secret_access_key) %>
#   region: us-east-1
#   bucket: your_own_bucket

# Remember not to checkin your GCS keyfile to a repository
# google:
#   service: GCS
#   project: your_project
#   credentials: <%= Rails.root.join("path/to/gcs.keyfile") %>
#   bucket: your_own_bucket

# Use rails credentials:edit to set the Azure Storage secret (as azure_storage:storage_access_key)
# microsoft:
#   service: AzureStorage
#   storage_account_name: your_account_name
#   storage_access_key: <%= Rails.application.credentials.dig(:azure_storage, :storage_access_key) %>
#   container: your_container_name

# mirror:
#   service: Mirror
#   primary: local
#   mirrors: [ amazon, google, microsoft ]

